version: '3'

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all
    silent: true

  package:
    desc: Package add-on
    silent: true
    cmds:
      - zip -r release/anki_restart.ankiaddon * -x "release/*" -x "Taskfile.yaml" -x "README.md" -x ".gitignore" -x "__pycache__/*"